name: Typescript Publish
on:
  release:
    types:
      - "created" # triggered by Bump Version creating a release
  workflow_dispatch:
jobs:
  typescript-release:
    uses: IronCoreLabs/workflows/.github/workflows/typescript-release.yaml@typescript-release-v1
    with:
      pre_publish_steps: "./build.js"
      publish_working_directory: "pkg"
    secrets: inherit
